`./manage.py migrate --run-syncdb` fixed things with DB that were broken